#!/usr/bin/python3
import os,sys,json
if os.environ.get('SLIDES_QUAL_NETWORK')=='offline':
 with open(os.environ['SLIDES_QUAL_TRANSPORT_LOG'],'a') as f:f.write(json.dumps({'tool':'ssh','mode':'offline'})+'\n')
 print('OFFLINE_SSH_TRANSPORT_DENIED',file=sys.stderr);sys.exit(99)
os.execv('/usr/bin/ssh',['/usr/bin/ssh']+sys.argv[1:])
